### PR TITLE
Added dotnet core example

### PR DESCRIPTION
**Pull request by framebassman**

### CODE REVIEW

**Comment by Workshop2** [comment]
I look forward to giving this a go :+1:

**Comment by framebassman** [comment]
So why you still didn't merge it?)

**Comment by Workshop2** [comment]
Hey @FrameBassman - I checked it on my phone but haven't had time to test it on a computer. Don't worry, I will look soon 👍

**Comment by framebassman** [comment]
Omg, sorry for inconvenience)

**Comment by framebassman** [comment]
> Opened 7 day ago

Cmon, it's not rocket science, just one more implementation

**Comment by Workshop2** [comment]
Thanks but it was submitted with incompatible libraries and i have been working on it today to get it working. I have been doing lots of work in other repos in preparation  a for this change so please be patient.

**Comment by Workshop2** [comment]
This has now been merged, Thanks for the help.

**Comment by framebassman** [comment]
Thank you)

**Pull request merged**
